### ISSUE TITLE
Redirect to HTTPS pages

### ISSUE THREAD

**Issue by theel0ja** [udlei/redirect.center#12]
Support for HTTPS.

**Comment by udlei** [comment]
@theel0ja I've tried a lot of solutions to implement https on top of redirect.center but it's not possible because I will need a certificate for your domain, not for redirect.center.

When you access https://yourdomain.com.br, this domain is configured to point to redirect.center server and there I don't have the certificate, even with letsencrypt I will need a small and sometimes manual process to configure each certificate to each new domain.

If your have any idea to solve this problem, let me know.

**Comment by theel0ja** [comment]
I meaned like this:

http://test.example.com -> https://redirect.to.this.page

**Comment by udlei** [comment]
@theel0ja it's ok now. Use:

www.my-domain.com.**opts-https**.redirect.center
